# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: konfou gh-pages
email: mail@konfou.xyz
description: >
  hosted on github.io (@ gh.konfou.xyz)
baseurl: ""
url: "http://gh.konfou.xyz"
twitter_username: konfou
github_username:  konfou

# Build settings
markdown: kramdown
