# site config
title: home/konfou
email: mail@konfou.xyz
description: a physicts venture into CS
url: "https://konfou.xyz"
excerpt_seperator: <!--more-->

# build config
markdown: kramdown
sass:
    style: :compressed
    sass_dir: _sass
permalink: /posts/:title/
gems:
    - jekyll-feed
    - jekyll-sitemap
timezone: Greece/Thessaloniki