# site config
title: konfou.xyz
description: a physicist's venture to a wibbly wobbly webey wimey internet
url: konfou.xyz
logo: /assets/img/sigil_konfou.xyz.png

# author info
author: Konstantinos Foutzopoulos
email: mail@konfou.xyz

# build config
include: ["_pages"]
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
sass:
    style: compressed
    sass_dir: _sass
permalink: /posts/:title/
gems:
    - jekyll-feed
    - jekyll-sitemap
timezone: Greece/Thessaloniki
