# site config
title: konfou.xyz
description: a physicists venture into the internet
url: konfou.xyz
logo: /assets/img/sigil_konfou.xyz.png

# author info
author: Konstantinos Foutzopoulos
email: mail@konfou.xyz

# build config
include: ["_pages"]
markdown: kramdown
sass:
    style: compressed
    sass_dir: _sass
permalink: /posts/:title/
gems:
    - jekyll-feed
    - jekyll-sitemap
timezone: Greece/Thessaloniki
